# Generated by Django 5.2 on 2025-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scale_choices',
            field=models.JSONField(blank=True, default=list, help_text="Формат: [['значение', 'описание'], ...]", null=True),
        ),
    ]
