# Generated by Django 5.2 on 2025-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
    ]
