# Generated by Django 5.2 on 2025-04-19 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback360', '0002_alter_question_scale_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
